FROM docker.io/n8nio/n8n:1.102.3

COPY _data /home/node/.n8n

USER root

RUN chmod -Rf 775 /home/node/.n8n/ && \
    chown -Rf node:node /home/node/.n8n

USER node
ENTRYPOINT ["tini", "--", "/docker-entrypoint.sh"]