FROM docker.io/pgvector/pgvector:pg17

ENV POSTGRES_USER=postgres \
    POSTGRES_PASSWORD=postgres \
    POSTGRES_DB=postgres


## To persist data - run manually: podman cp postgres:/var/lib/postgresql/data postgres/_data
# and uncomment these two:
#COPY _data /var/lib/postgresql/data
#RUN chmod -Rf 770 /var/lib/postgresql/data

# Copy the SQL files to the container
COPY ./initial-setup.sql /docker-entrypoint-initdb.d/


EXPOSE 5432

