FROM docker.io/pgvector/pgvector:pg17

ENV POSTGRES_USER=postgres \
    POSTGRES_PASSWORD=postgres \
    POSTGRES_DB=postgres


# Got data from: podman cp postgres:/var/lib/postgresql/data postgres/_data
COPY _data /var/lib/postgresql/data
RUN chmod -Rf 770 /var/lib/postgresql/data

EXPOSE 5432

